name: CD - Run Inference on Production Model

on:
  push:
    branches:
      - main

jobs:
  deploy-and-predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Data + Train (if needed)
        run: |
          python src/data_ingestion.py
          python src/data_cleaning.py
          python src/feature_engineering.py
          python src/train.py

      - name: Run Prediction from CSV
        run: |
          python src/batch_predict.py

      - name: CD Completed
        run: echo "CD Pipeline Completed ðŸš€"
